In [1]:
import pandas as pd
import numpy as np
from pandasql import sqldf
from scipy.stats.mstats import winsorize

In [2]:
df = pd.read_csv (r'D:\User\Desktop\thesis\data\blockholders\main data\main\Cleaned_Stocks_Holders Final version.csv')

C:\Users\masou\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (15,16) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
df=df.rename(columns={"name": "firm"})
df['year'] = (df[['jalaliDate']]/10000).astype(int)
df['Market_cap'] =df.apply(lambda row: ((row['shrout']*row['close_price'])/(10**6)),axis=1)
df

,Unnamed: 0,date,firm,jalaliDate,stock_id,group_name,group_id,Holder,Holder_id,nshares,type,Percent,shrout,close_price,Condition,Number_Change,Percent_Change,Trade,year,Market_cap
0,0,20110713,آ س پ,13900422,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,ثاخت,301.0,1.794020e+08,private,89.70,2.000000e+08,3100.0,Orginal,-,-,Yes,1390,620000.0
1,1,20110716,آ س پ,13900425,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,ثاخت,301.0,1.794020e+08,private,89.70,2.000000e+08,3252.0,Orginal,0.0,0.0,Yes,1390,650400.0
2,2,20110718,آ س پ,13900427,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,صندوق بیمه اجتماعی روستاییان و عشایر,771.0,2.171009e+06,pension,1.08,2.000000e+08,3264.0,Orginal,-,-,Yes,1390,652800.0
3,3,20110718,آ س پ,13900427,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,ثاخت,301.0,1.794020e+08,private,89.70,2.000000e+08,3264.0,Orginal,0.0,0.0,Yes,1390,652800.0
4,4,20110719,آ س پ,13900428,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,صندوق بیمه اجتماعی روستاییان و عشایر,771.0,3.128013e+06,pension,1.56,2.000000e+08,3203.0,Orginal,957004.0,0.48,Yes,1390,640600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10050241,10050241,20220214,یاقوت,14001125,1.438515e+15,صندوق سرمایه گذاری قابل معامله,68.0,صندوق بازارگردانی آگاه,62288.0,1.422521e+09,MM fund,47.41,4.000000e+09,14185.0,Orginal,-633368.0,-0.020000000000003126,Yes,1400,56740000.0
10050242,10050242,20220216,یاقوت,14001127,1.438515e+15,صندوق سرمایه گذاری قابل معامله,68.0,مشاورسرمایه گذاری آوای آگاه,50771.0,4.025000e+07,private,1.34,4.000000e+09,14197.0,Orginal,0.0,0.0,Yes,1400,56788000.0
10050243,10050243,20220216,یاقوت,14001127,1.438515e+15,صندوق سرمایه گذاری قابل معامله,68.0,ویستاسامانه آسا,51201.0,1.711022e+08,private,5.70,4.000000e+09,14197.0,Orginal,-20000000.0,-0.6699999999999999,Yes,1400,56788000.0
10050244,10050244,20220216,یاقوت,14001127,1.438515e+15,صندوق سرمایه گذاری قابل معامله,68.0,سبدگردان آگاه,51983.0,1.739107e+08,investment,5.79,4.000000e+09,14197.0,Orginal,0.0,0.0,Yes,1400,56788000.0
10050245,10050245,20220216,یاقوت,14001127,1.438515e+15,صندوق سرمایه گذاری قابل معامله,68.0,صندوق بازارگردانی آگاه,62288.0,1.422479e+09,MM fund,47.41,4.000000e+09,14197.0,Orginal,-41807.0,0.0,Yes,1400,56788000.0

In [4]:
df.drop(df[df['Percent'] < 5].index, inplace = True)

In [5]:
t = df[['Holder', 'Holder_id', 'type', 'firm','jalaliDate','year','Percent','Market_cap']]
t

,Holder,Holder_id,type,firm,jalaliDate,year,Percent,Market_cap
0,ثاخت,301.0,private,آ س پ,13900422,1390,89.70,620000.0
1,ثاخت,301.0,private,آ س پ,13900425,1390,89.70,650400.0
3,ثاخت,301.0,private,آ س پ,13900427,1390,89.70,652800.0
5,ثاخت,301.0,private,آ س پ,13900428,1390,89.70,640600.0
7,ثاخت,301.0,private,آ س پ,13900429,1390,89.70,629400.0
...,...,...,...,...,...,...,...,...
10050240,ویستاسامانه آسا,51201.0,private,یاقوت,14001125,1400,6.37,56740000.0
10050241,صندوق بازارگردانی آگاه,62288.0,MM fund,یاقوت,14001125,1400,47.41,56740000.0
10050243,ویستاسامانه آسا,51201.0,private,یاقوت,14001127,1400,5.70,56788000.0
10050244,سبدگردان آگاه,51983.0,investment,یاقوت,14001127,1400,5.79,56788000.0
10050245,صندوق بازارگردانی آگاه,62288.0,MM fund,یاقوت,14001127,1400,47.41,56788000.0

In [6]:
d=t.sort_values(by=['Holder', 'Holder_id','firm','year'])

In [7]:
edited=pd.read_excel(r'D:\User\Desktop\thesis\data\blockholders\change_type1.xlsx')
mapingdict = dict(zip(edited.type,edited.new_type))
d['type'] = d.type.map(mapingdict)     
d

,Holder,Holder_id,type,firm,jalaliDate,year,Percent,Market_cap
9993601,Donhauser GmbH,62590.0,private corportion,گدنا,13990529,1399,41.49,1800000.0
9993603,Donhauser GmbH,62590.0,private corportion,گدنا,13990601,1399,40.22,1801200.0
9993605,Donhauser GmbH,62590.0,private corportion,گدنا,13990602,1399,39.99,1816500.0
9993606,Donhauser GmbH,62590.0,private corportion,گدنا,13990603,1399,39.99,1818000.0
9993609,Donhauser GmbH,62590.0,private corportion,گدنا,13990604,1399,39.99,1819800.0
...,...,...,...,...,...,...,...,...
7624449,یکتا سرآمد گیتی,45349.0,private corportion,وحافظ,13980217,1398,8.03,1710196.0
7624468,یکتا سرآمد گیتی,45349.0,private corportion,وحافظ,13980218,1398,8.03,1771562.0
7624487,یکتا سرآمد گیتی,45349.0,private corportion,وحافظ,13980221,1398,8.03,1648830.0
7624506,یکتا سرآمد گیتی,45349.0,private corportion,وحافظ,13980222,1398,8.03,1538542.0
7624525,یکتا سرآمد گیتی,45349.0,private corportion,وحافظ,13980223,1398,8.03,1653832.0

In [8]:
gg = d.groupby(['Holder', 'Holder_id','type','year'])
def cc(g):
    
    return len(g['firm'].unique())
t = gg.apply(cc).to_frame().rename(columns = {0:"Firm_Number"})
def cc(g):
    return g['Percent'].mean()
t = t.merge(gg.apply(cc).to_frame().rename(columns = {0:"Mean_yearly_totalownership"}),left_index= True,    right_index=True)
t = t.reset_index()

t.to_excel (r'D:\User\Desktop\thesis\data\blockholders\main data\Holder\Holders_year_unique firm number.xlsx',index=False)

In [9]:
d['Mean_yearly_totalownership']=d.groupby(['Holder', 'Holder_id','type','year']).Percent.transform(np.mean)
d['Mean_yearly_firm_ownership']=d.groupby(['Holder', 'Holder_id','type','firm','year']).Percent.transform(np.mean)
d['Mean_yearly_marketcap']=d.groupby(['firm','year']).Market_cap.transform(np.mean)
t = d.drop_duplicates(subset=['Holder','Holder_id','type','year','firm'],keep='last').sort_values(by = ['Holder','year'])
t.rename(columns={"Percent": "End_year_Percent"}, inplace = True)
t.rename(columns={"Market_cap": "End_year_Market_cap"}, inplace = True)
#t['End_year_Market_cap']=winsorize(t['End_year_Market_cap'],limits=[0.01, 0.01])
#t['Mean_yearly_marketcap']=winsorize(t['Mean_yearly_marketcap'],limits=[0.01, 0.01])
t.to_excel (r'D:\User\Desktop\thesis\data\blockholders\main data\Holder\TSE_HOLDERSS_FIRM_YEAR.xlsx',index=False)

In [10]:
dff=t.sort_values(by=['Holder', 'Holder_id','firm','year'])

In [11]:
df_sorted=dff.sort_values(by=['Holder','year'])
df_sorted

,Holder,Holder_id,type,firm,jalaliDate,year,End_year_Percent,End_year_Market_cap,Mean_yearly_totalownership,Mean_yearly_firm_ownership,Mean_yearly_marketcap
9993950,Donhauser GmbH,62590.0,private corportion,گدنا,13991227,1399,34.99,1.021440e+07,37.514236,37.514236,7.459673e+06
9994782,Donhauser GmbH,62590.0,private corportion,گدنا,14001127,1400,29.99,3.351000e+06,34.830183,34.830183,6.242253e+06
2218369,FIN Zf Friedrichshafen Ag,71127.0,private corportion,خچرخش,14001127,1400,16.69,5.046102e+06,16.690000,16.690000,1.073982e+07
106417,Gif Spc,48571.0,private corportion,آسامید,13991218,1399,5.36,1.164300e+06,12.363503,5.621087,1.074452e+06
290794,Gif Spc,48571.0,private corportion,افران,13991227,1399,6.78,6.457500e+06,12.363503,14.417483,2.050998e+06
...,...,...,...,...,...,...,...,...,...,...,...
7213024,یاس مدینه نور,8026.0,private corportion,وانصار,13901228,1390,5.00,1.123600e+07,5.000000,5.000000,1.137731e+07
7213807,یاس مدینه نور,8026.0,private corportion,وانصار,13910421,1391,5.00,1.000000e+07,5.000000,5.000000,9.188202e+06
7619702,یکتا سرآمد گیتی,45349.0,private corportion,وحافظ,13961228,1396,23.55,3.904000e+05,26.016653,26.016653,3.890218e+05
7623917,یکتا سرآمد گیتی,45349.0,private corportion,وحافظ,13971228,1397,8.03,1.344562e+06,13.452324,13.452324,9.491936e+05
7624525,یکتا سرآمد گیتی,45349.0,private corportion,وحافظ,13980223,1398,8.03,1.653832e+06,8.030000,8.030000,2.153715e+06

In [12]:
new_df = pd.DataFrame(columns=['Holder','Holder_id','type','Year','Turnover'])
Holder = []
Holder_id = []
type = []
Year = []
Turnover = []
new_df

Empty DataFrame
Columns: [Holder, Holder_id, type, Year, Turnover]
Index: []

In [13]:
summation = 0
summation_denom = 0
for i in range(len(df_sorted)) : 
    if i == 0 : 
        summation += (df_sorted.iloc[i][10]) * (df_sorted.iloc[i][6])
        summation_denom += 0.5 * (df_sorted.iloc[i][10]) * (df_sorted.iloc[i][6])
    else : 
          cond = True
          ind = 1
          if df_sorted.iloc[i][5] != df_sorted.iloc[i-1][5] or df_sorted.iloc[i][1] != df_sorted.iloc[i-1][1]  :
            turnover = summation / summation_denom
            summation = 0
            summation_denom = 0
            Holder.append(df_sorted.iloc[i-1][0])
            Holder_id.append(df_sorted.iloc[i-1][1])
            type.append(df_sorted.iloc[i-1][2])
            Year.append(df_sorted.iloc[i-1][5])
            Turnover.append(turnover)
          while cond :
            if  df_sorted.iloc[i][1] == df_sorted.iloc[i-ind][1] :
                if df_sorted.iloc[i][5] == df_sorted.iloc[i-ind][5] + 1 and df_sorted.iloc[i][3] == df_sorted.iloc[i-ind][3] : 
                    summation += (df_sorted.iloc[i][10]) * np.abs(df_sorted.iloc[i][6]- df_sorted.iloc[i-ind][6])
                    summation_denom += 0.5 * (((df_sorted.iloc[i][10]) * (df_sorted.iloc[i][6])) + (df_sorted.iloc[i-ind][10] * (df_sorted.iloc[i-ind][6])))
                    cond = False
                else :
                      ind += 1
            else :
                  cond = False
                  summation += (df_sorted.iloc[i][10]) * (df_sorted.iloc[i][6])
                  summation_denom += 0.5 * (df_sorted.iloc[i][10]) * (df_sorted.iloc[i][6])
    if i == len(df_sorted) - 1 : 
              ind = 1 
              if df_sorted.iloc[i][1] == df_sorted.iloc[i-ind][1] :
                  if df_sorted.iloc[i][5] == df_sorted.iloc[i-ind][5] + 1 and df_sorted.iloc[i][3] == df_sorted.iloc[i-ind][3] : 
                    summation += (df_sorted.iloc[i][10]) * np.abs(df_sorted.iloc[i][6]- df_sorted.iloc[i-ind][6])
                    summation_denom += 0.5 * (((df_sorted.iloc[i][10]) * (df_sorted.iloc[i][6])) + (df_sorted.iloc[i-ind][10] * (df_sorted.iloc[i-ind][6])))
                    turnover = summation / summation_denom
                    Holder.append(df_sorted.iloc[i][0])
                    Year.append(df_sorted.iloc[i][5])
                    Turnover.append(turnover)
                  else : 
                        ind += 1
              else :
                    summation += (df_sorted.iloc[i][10]) * (df_sorted.iloc[i][6])
                    summation_denom += 0.5 * (df_sorted.iloc[i][10]) * (df_sorted.iloc[i][6])
                    turnover = summation / summation_denom
                    summation = 0
                    summation_denom = 0
                    Holder.append(df_sorted.iloc[i][0])
                    Holder_id.append(df_sorted.iloc[i-1][1])
                    type.append(df_sorted.iloc[i-1][2])
                    Year.append(df_sorted.iloc[i][5])
                    Turnover.append(turnover)

In [14]:
new_df['Holder'] = pd.Series(Holder)
new_df['Holder_id'] = pd.Series(Holder_id)
new_df['type'] = pd.Series(type)
new_df['Year'] = pd.Series(Year)
new_df['Turnover'] = pd.Series(Turnover)
new_df.head(20)

                       Holder  Holder_id                type  Year  Turnover
0              Donhauser GmbH    62590.0  private corportion  1399  2.000000
1              Donhauser GmbH    62590.0  private corportion  1400  0.139268
2   FIN Zf Friedrichshafen Ag    71127.0  private corportion  1400  2.000000
3                     Gif Spc    48571.0  private corportion  1399  2.000000
4                     Gif Spc    48571.0  private corportion  1400  0.292789
5                NokiaSiemens      566.0  private corportion  1387  2.000000
6                NokiaSiemens      566.0  private corportion  1388  0.000000
7                NokiaSiemens      566.0  private corportion  1389  0.000000
8                NokiaSiemens      566.0  private corportion  1390  0.000000
9                NokiaSiemens      566.0  private corportion  1391  0.000000
10             SANIL ELECTRIC    44684.0  private corportion  1395  2.000000
11             SANIL ELECTRIC    44684.0  private corportion  1396  0.658254
12             SANIL ELECTRIC    44684.0  private corportion  1397  0.000000
13             SANIL ELECTRIC    44684.0  private corportion  1398  0.000000
14             SANIL ELECTRIC    44684.0  private corportion  1399  0.000000
15             SANIL ELECTRIC    44684.0  private corportion  1400  0.000000
16      آتیه اندیشان سپهر شرق    71026.0  private corportion  1400  2.000000
17   آتیه سازان امیدنسل امروز    42374.0  private corportion  1395  2.000000
18   آتیه سازان امیدنسل امروز    42374.0  private corportion  1396  0.000000
19   آتیه سازان امیدنسل امروز    42374.0  private corportion  1397  0.001435

In [15]:
new_df.to_excel (r'D:\User\Desktop\thesis\data\blockholders\main data\Holder\turnover_measure.xlsx',index=False)

In [17]:
from pandasql import sqldf
pysqldf = lambda q: sqldf(q, globals())
df = pd.read_excel (r'D:\User\Desktop\thesis\data\blockholders\main data\Holder\Holders_year_unique firm number.xlsx')
dd = pd.read_excel (r'D:\User\Desktop\thesis\data\blockholders\main data\Holder\turnover_measure.xlsx')
q = '''
SELECT dd.Turnover
FROM dd,df
WHERE dd.Holder = df.Holder AND dd.Holder_id = df.Holder_id AND  dd.type = df.type AND dd.year = df.year
'''
names = (pysqldf(q))
list_turnover = list(names['Turnover'])
df['Turnover_measure'] = list_turnover

In [18]:
df['Portfo_size'] = '1'
df.loc[df.Firm_Number > 1,'Portfo_size'] = '2'
df.loc[df.Firm_Number > 2,'Portfo_size'] = '3-5'
df.loc[df.Firm_Number > 5,'Portfo_size'] = '>5'

df['Turnover_type'] = 'Long-term'
df.loc[df.Turnover_measure > 0.5,'Turnover_type'] = 'Medium-term2'
df.loc[df.Turnover_measure > 0.1,'Turnover_type'] = 'Medium-term1'
df.loc[df.Turnover_measure  > 1.5,'Turnover_type'] = 'Short-term'

df.to_excel (r'D:\User\Desktop\thesis\data\blockholders\main data\Holder\Holder_characteristic.xlsx',index=False)